/**
 * Agave Platform Science API
 * Power your digital lab and reduce the time from theory to discovery using the Agave Science-as-a-Service API Platform. Agave provides hosted services that allow researchers to manage data, conduct experiments, and publish and share results from anywhere at any time.
 *
 * OpenAPI spec version: 2.2.14
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'Model/ClientSubscriptionTier'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ClientSubscriptionTier'));
  } else {
    // Browser globals (root is window)
    if (!root.AgaveJsSdk) {
      root.AgaveJsSdk = {};
    }
    root.AgaveJsSdk.ClientRequest = factory(root.AgaveJsSdk.ApiClient, root.AgaveJsSdk.ClientSubscriptionTier);
  }
}(this, function(ApiClient, ClientSubscriptionTier) {
  'use strict';




  /**
   * The ClientRequest model module.
   * @module Model/ClientRequest
   * @version 0.1.0
   */

  /**
   * Constructs a new <code>ClientRequest</code>.
   * @alias module:Model/ClientRequest
   * @class
   * @param name {String} The name of the client.
   * @param description {String} Description of the client. This will be shown to users when authentication via OAuth web flows
   * @param tier {module:Model/ClientSubscriptionTier} 
   * @param callbackUrl {String} Callback URL for OAuth authentication grant.
   */
  var exports = function(name, description, tier, callbackUrl) {
    var _this = this;

    _this['name'] = name;
    _this['description'] = description;
    _this['tier'] = tier;
    _this['callbackUrl'] = callbackUrl;
  };

  /**
   * Constructs a <code>ClientRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:Model/ClientRequest} obj Optional instance to populate.
   * @return {module:Model/ClientRequest} The populated <code>ClientRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('description')) {
        obj['description'] = ApiClient.convertToType(data['description'], 'String');
      }
      if (data.hasOwnProperty('tier')) {
        obj['tier'] = ClientSubscriptionTier.constructFromObject(data['tier']);
      }
      if (data.hasOwnProperty('callbackUrl')) {
        obj['callbackUrl'] = ApiClient.convertToType(data['callbackUrl'], 'String');
      }
    }
    return obj;
  }

  /**
   * The name of the client.
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * Description of the client. This will be shown to users when authentication via OAuth web flows
   * @member {String} description
   */
  exports.prototype['description'] = undefined;
  /**
   * @member {module:Model/ClientSubscriptionTier} tier
   */
  exports.prototype['tier'] = undefined;
  /**
   * Callback URL for OAuth authentication grant.
   * @member {String} callbackUrl
   */
  exports.prototype['callbackUrl'] = undefined;



  return exports;
}));


