/**
 * Agave Platform Science API
 * Power your digital lab and reduce the time from theory to discovery using the Agave Science-as-a-Service API Platform. Agave provides hosted services that allow researchers to manage data, conduct experiments, and publish and share results from anywhere at any time.
 *
 * OpenAPI spec version: 2.2.14
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'Model/PermissionStanza'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./PermissionStanza'));
  } else {
    // Browser globals (root is window)
    if (!root.AgaveJsSdk) {
      root.AgaveJsSdk = {};
    }
    root.AgaveJsSdk.FilePermissionStanza = factory(root.AgaveJsSdk.ApiClient, root.AgaveJsSdk.PermissionStanza);
  }
}(this, function(ApiClient, PermissionStanza) {
  'use strict';




  /**
   * The FilePermissionStanza model module.
   * @module Model/FilePermissionStanza
   * @version 0.1.0
   */

  /**
   * Constructs a new <code>FilePermissionStanza</code>.
   * A permission object describing read, write, and execute permission for a file item.
   * @alias module:Model/FilePermissionStanza
   * @class
   * @implements module:Model/PermissionStanza
   * @param read {Boolean} Is the resource readable
   * @param write {Boolean} Is the resource writable
   */
  var exports = function(read, write) {
    var _this = this;

    PermissionStanza.call(_this, read, write);
  };

  /**
   * Constructs a <code>FilePermissionStanza</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:Model/FilePermissionStanza} obj Optional instance to populate.
   * @return {module:Model/FilePermissionStanza} The populated <code>FilePermissionStanza</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      PermissionStanza.constructFromObject(data, obj);
    }
    return obj;
  }


  // Implement PermissionStanza interface:
  /**
   * Is the resource readable
   * @member {Boolean} read
   * @default false
   */
exports.prototype['read'] = false;

  /**
   * Is the resource writable
   * @member {Boolean} write
   * @default false
   */
exports.prototype['write'] = false;



  return exports;
}));


