/**
 * Agave Platform Science API
 * Power your digital lab and reduce the time from theory to discovery using the Agave Science-as-a-Service API Platform. Agave provides hosted services that allow researchers to manage data, conduct experiments, and publish and share results from anywhere at any time.
 *
 * OpenAPI spec version: 2.2.14
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'Model/JobActionType'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./JobActionType'));
  } else {
    // Browser globals (root is window)
    if (!root.AgaveJsSdk) {
      root.AgaveJsSdk = {};
    }
    root.AgaveJsSdk.JobAction = factory(root.AgaveJsSdk.ApiClient, root.AgaveJsSdk.JobActionType);
  }
}(this, function(ApiClient, JobActionType) {
  'use strict';




  /**
   * The JobAction model module.
   * @module Model/JobAction
   * @version 0.1.0
   */

  /**
   * Constructs a new <code>JobAction</code>.
   * Requests that a management action take place against a job.
   * @alias module:Model/JobAction
   * @class
   * @param action {module:Model/JobActionType} 
   */
  var exports = function(action) {
    var _this = this;

    _this['action'] = action;
  };

  /**
   * Constructs a <code>JobAction</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:Model/JobAction} obj Optional instance to populate.
   * @return {module:Model/JobAction} The populated <code>JobAction</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('action')) {
        obj['action'] = JobActionType.constructFromObject(data['action']);
      }
    }
    return obj;
  }

  /**
   * @member {module:Model/JobActionType} action
   */
  exports.prototype['action'] = undefined;



  return exports;
}));


