/**
 * Agave Platform Science API
 * Power your digital lab and reduce the time from theory to discovery using the Agave Science-as-a-Service API Platform. Agave provides hosted services that allow researchers to manage data, conduct experiments, and publish and share results from anywhere at any time.
 *
 * OpenAPI spec version: 2.2.14
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.AgaveJsSdk) {
      root.AgaveJsSdk = {};
    }
    root.AgaveJsSdk.Metadata = factory(root.AgaveJsSdk.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Metadata model module.
   * @module Model/Metadata
   * @version 0.1.0
   */

  /**
   * Constructs a new <code>Metadata</code>.
   * @alias module:Model/Metadata
   * @class
   * @param associationIds {Array.<String>} UUIDs of associated Agave entities, including the Data to which this Metadata belongs.
   * @param created {Date} A timestamp indicating when this Metadata was created in the metadata store.
   * @param internalUsername {String} The name of the Internal User, if any, who owns this metadata.
   * @param lastUpdated {Date} A timestamp indicating when this Metadata was last updated in the metadata store.
   * @param name {String} The name of this metadata
   * @param owner {String} The API user who owns this Metadata.
   * @param uuid {String} The UUID for this Metadata.
   * @param value {String} A free text or JSON string containing the metadata stored for the given associationIds
   */
  var exports = function(associationIds, created, internalUsername, lastUpdated, name, owner, uuid, value) {
    var _this = this;

    _this['associationIds'] = associationIds;
    _this['created'] = created;
    _this['internalUsername'] = internalUsername;
    _this['lastUpdated'] = lastUpdated;
    _this['name'] = name;
    _this['owner'] = owner;
    _this['uuid'] = uuid;
    _this['value'] = value;
  };

  /**
   * Constructs a <code>Metadata</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:Model/Metadata} obj Optional instance to populate.
   * @return {module:Model/Metadata} The populated <code>Metadata</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('associationIds')) {
        obj['associationIds'] = ApiClient.convertToType(data['associationIds'], ['String']);
      }
      if (data.hasOwnProperty('created')) {
        obj['created'] = ApiClient.convertToType(data['created'], 'Date');
      }
      if (data.hasOwnProperty('internalUsername')) {
        obj['internalUsername'] = ApiClient.convertToType(data['internalUsername'], 'String');
      }
      if (data.hasOwnProperty('lastUpdated')) {
        obj['lastUpdated'] = ApiClient.convertToType(data['lastUpdated'], 'Date');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('owner')) {
        obj['owner'] = ApiClient.convertToType(data['owner'], 'String');
      }
      if (data.hasOwnProperty('uuid')) {
        obj['uuid'] = ApiClient.convertToType(data['uuid'], 'String');
      }
      if (data.hasOwnProperty('value')) {
        obj['value'] = ApiClient.convertToType(data['value'], 'String');
      }
    }
    return obj;
  }

  /**
   * UUIDs of associated Agave entities, including the Data to which this Metadata belongs.
   * @member {Array.<String>} associationIds
   */
  exports.prototype['associationIds'] = undefined;
  /**
   * A timestamp indicating when this Metadata was created in the metadata store.
   * @member {Date} created
   */
  exports.prototype['created'] = undefined;
  /**
   * The name of the Internal User, if any, who owns this metadata.
   * @member {String} internalUsername
   */
  exports.prototype['internalUsername'] = undefined;
  /**
   * A timestamp indicating when this Metadata was last updated in the metadata store.
   * @member {Date} lastUpdated
   */
  exports.prototype['lastUpdated'] = undefined;
  /**
   * The name of this metadata
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * The API user who owns this Metadata.
   * @member {String} owner
   */
  exports.prototype['owner'] = undefined;
  /**
   * The UUID for this Metadata.
   * @member {String} uuid
   */
  exports.prototype['uuid'] = undefined;
  /**
   * A free text or JSON string containing the metadata stored for the given associationIds
   * @member {String} value
   */
  exports.prototype['value'] = undefined;



  return exports;
}));


