/**
 * Agave Platform Science API
 * Power your digital lab and reduce the time from theory to discovery using the Agave Science-as-a-Service API Platform. Agave provides hosted services that allow researchers to manage data, conduct experiments, and publish and share results from anywhere at any time.
 *
 * OpenAPI spec version: 2.2.14
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'Model/MonitorCheckResultType'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./MonitorCheckResultType'));
  } else {
    // Browser globals (root is window)
    if (!root.AgaveJsSdk) {
      root.AgaveJsSdk = {};
    }
    root.AgaveJsSdk.MonitoringTaskCheck = factory(root.AgaveJsSdk.ApiClient, root.AgaveJsSdk.MonitorCheckResultType);
  }
}(this, function(ApiClient, MonitorCheckResultType) {
  'use strict';




  /**
   * The MonitoringTaskCheck model module.
   * @module Model/MonitoringTaskCheck
   * @version 0.1.0
   */

  /**
   * Constructs a new <code>MonitoringTaskCheck</code>.
   * An individual check made for a monitoring task. 
   * @alias module:Model/MonitoringTaskCheck
   * @class
   * @param created {Date} A timestamp indicating when this monitor check was created.
   * @param id {String} The UUID for this monitor check.
   * @param message {String} The error message if this monitor check failed.
   * @param result {module:Model/MonitorCheckResultType} 
   */
  var exports = function(created, id, message, result) {
    var _this = this;

    _this['created'] = created;
    _this['id'] = id;
    _this['message'] = message;
    _this['result'] = result;
  };

  /**
   * Constructs a <code>MonitoringTaskCheck</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:Model/MonitoringTaskCheck} obj Optional instance to populate.
   * @return {module:Model/MonitoringTaskCheck} The populated <code>MonitoringTaskCheck</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('created')) {
        obj['created'] = ApiClient.convertToType(data['created'], 'Date');
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('message')) {
        obj['message'] = ApiClient.convertToType(data['message'], 'String');
      }
      if (data.hasOwnProperty('result')) {
        obj['result'] = MonitorCheckResultType.constructFromObject(data['result']);
      }
    }
    return obj;
  }

  /**
   * A timestamp indicating when this monitor check was created.
   * @member {Date} created
   */
  exports.prototype['created'] = undefined;
  /**
   * The UUID for this monitor check.
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * The error message if this monitor check failed.
   * @member {String} message
   */
  exports.prototype['message'] = undefined;
  /**
   * @member {module:Model/MonitorCheckResultType} result
   */
  exports.prototype['result'] = undefined;



  return exports;
}));


