/**
 * Agave Platform Science API
 * Power your digital lab and reduce the time from theory to discovery using the Agave Science-as-a-Service API Platform. Agave provides hosted services that allow researchers to manage data, conduct experiments, and publish and share results from anywhere at any time.
 *
 * OpenAPI spec version: 2.2.14
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'Model/PermissionStanza'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./PermissionStanza'));
  } else {
    // Browser globals (root is window)
    if (!root.AgaveJsSdk) {
      root.AgaveJsSdk = {};
    }
    root.AgaveJsSdk.Permission = factory(root.AgaveJsSdk.ApiClient, root.AgaveJsSdk.PermissionStanza);
  }
}(this, function(ApiClient, PermissionStanza) {
  'use strict';




  /**
   * The Permission model module.
   * @module Model/Permission
   * @version 0.1.0
   */

  /**
   * Constructs a new <code>Permission</code>.
   * A generic permission applied to any resource in the API
   * @alias module:Model/Permission
   * @class
   * @param username {String} The username to whom this permission grant applies
   * @param permission {module:Model/PermissionStanza} 
   * @param created {Date} The date the permission was created
   * @param lastUpdated {Date} The date the permission was last updated
   * @param id {String} The unique id of this permission
   */
  var exports = function(username, permission, created, lastUpdated, id) {
    var _this = this;

    _this['username'] = username;

    _this['permission'] = permission;
    _this['created'] = created;
    _this['lastUpdated'] = lastUpdated;
    _this['id'] = id;
  };

  /**
   * Constructs a <code>Permission</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:Model/Permission} obj Optional instance to populate.
   * @return {module:Model/Permission} The populated <code>Permission</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('username')) {
        obj['username'] = ApiClient.convertToType(data['username'], 'String');
      }
      if (data.hasOwnProperty('internalUsername')) {
        obj['internalUsername'] = ApiClient.convertToType(data['internalUsername'], 'String');
      }
      if (data.hasOwnProperty('permission')) {
        obj['permission'] = PermissionStanza.constructFromObject(data['permission']);
      }
      if (data.hasOwnProperty('created')) {
        obj['created'] = ApiClient.convertToType(data['created'], 'Date');
      }
      if (data.hasOwnProperty('lastUpdated')) {
        obj['lastUpdated'] = ApiClient.convertToType(data['lastUpdated'], 'Date');
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
    }
    return obj;
  }

  /**
   * The username to whom this permission grant applies
   * @member {String} username
   */
  exports.prototype['username'] = undefined;
  /**
   * The internal user associated with this permission
   * @member {String} internalUsername
   */
  exports.prototype['internalUsername'] = undefined;
  /**
   * @member {module:Model/PermissionStanza} permission
   */
  exports.prototype['permission'] = undefined;
  /**
   * The date the permission was created
   * @member {Date} created
   */
  exports.prototype['created'] = undefined;
  /**
   * The date the permission was last updated
   * @member {Date} lastUpdated
   */
  exports.prototype['lastUpdated'] = undefined;
  /**
   * The unique id of this permission
   * @member {String} id
   */
  exports.prototype['id'] = undefined;



  return exports;
}));


