/**
 * Agave Platform Science API
 * Power your digital lab and reduce the time from theory to discovery using the Agave Science-as-a-Service API Platform. Agave provides hosted services that allow researchers to manage data, conduct experiments, and publish and share results from anywhere at any time.
 *
 * OpenAPI spec version: 2.2.14
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'Model/SystemRoleType'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./SystemRoleType'));
  } else {
    // Browser globals (root is window)
    if (!root.AgaveJsSdk) {
      root.AgaveJsSdk = {};
    }
    root.AgaveJsSdk.SystemRoleRequest = factory(root.AgaveJsSdk.ApiClient, root.AgaveJsSdk.SystemRoleType);
  }
}(this, function(ApiClient, SystemRoleType) {
  'use strict';




  /**
   * The SystemRoleRequest model module.
   * @module Model/SystemRoleRequest
   * @version 0.1.0
   */

  /**
   * Constructs a new <code>SystemRoleRequest</code>.
   * A basic role granted to a user for a particular system
   * @alias module:Model/SystemRoleRequest
   * @class
   * @param username {String} The username of the api user granted this role.
   * @param role {module:Model/SystemRoleType} 
   */
  var exports = function(username, role) {
    var _this = this;

    _this['username'] = username;
    _this['role'] = role;
  };

  /**
   * Constructs a <code>SystemRoleRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:Model/SystemRoleRequest} obj Optional instance to populate.
   * @return {module:Model/SystemRoleRequest} The populated <code>SystemRoleRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('username')) {
        obj['username'] = ApiClient.convertToType(data['username'], 'String');
      }
      if (data.hasOwnProperty('role')) {
        obj['role'] = SystemRoleType.constructFromObject(data['role']);
      }
    }
    return obj;
  }

  /**
   * The username of the api user granted this role.
   * @member {String} username
   */
  exports.prototype['username'] = undefined;
  /**
   * @member {module:Model/SystemRoleType} role
   */
  exports.prototype['role'] = undefined;



  return exports;
}));


