/**
 * Agave Platform Science API
 * Power your digital lab and reduce the time from theory to discovery using the Agave Science-as-a-Service API Platform. Agave provides hosted services that allow researchers to manage data, conduct experiments, and publish and share results from anywhere at any time.
 *
 * OpenAPI spec version: 2.2.14
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.AgaveJsSdk) {
      root.AgaveJsSdk = {};
    }
    root.AgaveJsSdk.UUIDResolution = factory(root.AgaveJsSdk.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The UUIDResolution model module.
   * @module Model/UUIDResolution
   * @version 0.1.0
   */

  /**
   * Constructs a new <code>UUIDResolution</code>.
   * Resource to which a tag has been associated
   * @alias module:Model/UUIDResolution
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>UUIDResolution</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:Model/UUIDResolution} obj Optional instance to populate.
   * @return {module:Model/UUIDResolution} The populated <code>UUIDResolution</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('uuid')) {
        obj['uuid'] = ApiClient.convertToType(data['uuid'], 'String');
      }
      if (data.hasOwnProperty('type')) {
        obj['type'] = ApiClient.convertToType(data['type'], 'String');
      }
      if (data.hasOwnProperty('representation')) {
        obj['representation'] = ApiClient.convertToType(data['representation'], Object);
      }
    }
    return obj;
  }

  /**
   * uuid created/requested
   * @member {String} uuid
   */
  exports.prototype['uuid'] = undefined;
  /**
   * the resource type represented by this uuid
   * @member {String} type
   */
  exports.prototype['type'] = undefined;
  /**
   * the full object representation for this uuid
   * @member {Object} representation
   */
  exports.prototype['representation'] = undefined;



  return exports;
}));


