/**
 * Agave Platform Science API
 * Power your digital lab and reduce the time from theory to discovery using the Agave Science-as-a-Service API Platform. Agave provides hosted services that allow researchers to manage data, conduct experiments, and publish and share results from anywhere at any time.
 *
 * OpenAPI spec version: 2.2.14
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AgaveJsSdk);
  }
}(this, function(expect, AgaveJsSdk) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new AgaveJsSdk.SystemRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SystemRequest', function() {
    it('should create an instance of SystemRequest', function() {
      // uncomment below and update the code to test SystemRequest
      //var instance = new AgaveJsSdk.SystemRequest();
      //expect(instance).to.be.a(AgaveJsSdk.SystemRequest);
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instance = new AgaveJsSdk.SystemRequest();
      //expect(instance).to.be();
    });

    it('should have the property environment (base name: "environment")', function() {
      // uncomment below and update the code to test the property environment
      //var instance = new AgaveJsSdk.SystemRequest();
      //expect(instance).to.be();
    });

    it('should have the property executionType (base name: "executionType")', function() {
      // uncomment below and update the code to test the property executionType
      //var instance = new AgaveJsSdk.SystemRequest();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new AgaveJsSdk.SystemRequest();
      //expect(instance).to.be();
    });

    it('should have the property login (base name: "login")', function() {
      // uncomment below and update the code to test the property login
      //var instance = new AgaveJsSdk.SystemRequest();
      //expect(instance).to.be();
    });

    it('should have the property maxSystemJobs (base name: "maxSystemJobs")', function() {
      // uncomment below and update the code to test the property maxSystemJobs
      //var instance = new AgaveJsSdk.SystemRequest();
      //expect(instance).to.be();
    });

    it('should have the property maxSystemJobsPerUser (base name: "maxSystemJobsPerUser")', function() {
      // uncomment below and update the code to test the property maxSystemJobsPerUser
      //var instance = new AgaveJsSdk.SystemRequest();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new AgaveJsSdk.SystemRequest();
      //expect(instance).to.be();
    });

    it('should have the property queues (base name: "queues")', function() {
      // uncomment below and update the code to test the property queues
      //var instance = new AgaveJsSdk.SystemRequest();
      //expect(instance).to.be();
    });

    it('should have the property scheduler (base name: "scheduler")', function() {
      // uncomment below and update the code to test the property scheduler
      //var instance = new AgaveJsSdk.SystemRequest();
      //expect(instance).to.be();
    });

    it('should have the property scratchDir (base name: "scratchDir")', function() {
      // uncomment below and update the code to test the property scratchDir
      //var instance = new AgaveJsSdk.SystemRequest();
      //expect(instance).to.be();
    });

    it('should have the property site (base name: "site")', function() {
      // uncomment below and update the code to test the property site
      //var instance = new AgaveJsSdk.SystemRequest();
      //expect(instance).to.be();
    });

    it('should have the property startupScript (base name: "startupScript")', function() {
      // uncomment below and update the code to test the property startupScript
      //var instance = new AgaveJsSdk.SystemRequest();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instance = new AgaveJsSdk.SystemRequest();
      //expect(instance).to.be();
    });

    it('should have the property storage (base name: "storage")', function() {
      // uncomment below and update the code to test the property storage
      //var instance = new AgaveJsSdk.SystemRequest();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new AgaveJsSdk.SystemRequest();
      //expect(instance).to.be();
    });

    it('should have the property workDir (base name: "workDir")', function() {
      // uncomment below and update the code to test the property workDir
      //var instance = new AgaveJsSdk.SystemRequest();
      //expect(instance).to.be();
    });

  });

}));
