/**
 * Agave Platform Science API
 * Power your digital lab and reduce the time from theory to discovery using the Agave Science-as-a-Service API Platform. Agave provides hosted services that allow researchers to manage data, conduct experiments, and publish and share results from anywhere at any time.
 *
 * OpenAPI spec version: 2.2.14
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AgaveJsSdk);
  }
}(this, function(expect, AgaveJsSdk) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new AgaveJsSdk.AppsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AppsApi', function() {
    describe('addApp', function() {
      it('should call addApp successfully', function(done) {
        //uncomment below and update the code to test addApp
        //instance.addApp(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('addAppPermission', function() {
      it('should call addAppPermission successfully', function(done) {
        //uncomment below and update the code to test addAppPermission
        //instance.addAppPermission(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('clearAppPermissions', function() {
      it('should call clearAppPermissions successfully', function(done) {
        //uncomment below and update the code to test clearAppPermissions
        //instance.clearAppPermissions(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteApp', function() {
      it('should call deleteApp successfully', function(done) {
        //uncomment below and update the code to test deleteApp
        //instance.deleteApp(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteAppPermission', function() {
      it('should call deleteAppPermission successfully', function(done) {
        //uncomment below and update the code to test deleteAppPermission
        //instance.deleteAppPermission(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAppDetails', function() {
      it('should call getAppDetails successfully', function(done) {
        //uncomment below and update the code to test getAppDetails
        //instance.getAppDetails(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAppPermission', function() {
      it('should call getAppPermission successfully', function(done) {
        //uncomment below and update the code to test getAppPermission
        //instance.getAppPermission(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAppSubmissionForm', function() {
      it('should call getAppSubmissionForm successfully', function(done) {
        //uncomment below and update the code to test getAppSubmissionForm
        //instance.getAppSubmissionForm(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('invokeAppAction', function() {
      it('should call invokeAppAction successfully', function(done) {
        //uncomment below and update the code to test invokeAppAction
        //instance.invokeAppAction(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listAppHistory', function() {
      it('should call listAppHistory successfully', function(done) {
        //uncomment below and update the code to test listAppHistory
        //instance.listAppHistory(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listAppPermissions', function() {
      it('should call listAppPermissions successfully', function(done) {
        //uncomment below and update the code to test listAppPermissions
        //instance.listAppPermissions(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listApps', function() {
      it('should call listApps successfully', function(done) {
        //uncomment below and update the code to test listApps
        //instance.listApps(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateApp', function() {
      it('should call updateApp successfully', function(done) {
        //uncomment below and update the code to test updateApp
        //instance.updateApp(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateAppPermission', function() {
      it('should call updateAppPermission successfully', function(done) {
        //uncomment below and update the code to test updateAppPermission
        //instance.updateAppPermission(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
